apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:alpine
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d/jokes.sql
            name: config-volume
            subPath: jokes.sql
        env:
          - name: POSTGRES_PASSWORD
            value: example
          - name: POSTGRES_DB
            value: jokes
      volumes:
        - configMap:
            name: jokes
          name: config-volume
