apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
spec:
  ports:
  - name: sql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: database
  type: ClusterIP