apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: internal
        image: golang-http-example:latest
        imagePullPolicy: Always
        env:
          - name: DB_USER_NAME
            value: "postgres"
          - name: DB_PASSWORD
            value: "example"
          - name: DB_NAMES
            value: "jokes"
          - name: DB_PORT
            value: "5432"
          - name: DB_HOST
            value: "database.default"